FROM python:3.12

# Copy the entire project directory into /app
COPY . /app/

# Make scripts executable
RUN chmod +x /app/run.sh

# Set working directory
WORKDIR /app

# Install requirements
RUN pip install -r requirements.txt

CMD ["/app/run.sh", "discord"]