name: Run tests and upload coverage

on:
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    env:
      MONGO_CONNECTION_URL: ${{secrets.MONGO_CONNECTION_URL}}
      DB_NAME: ${{secrets.DB_NAME}}
      TELEGRAM_API_KEY: ${{secrets.TELEGRAM_API_KEY}}
      GMAIL_ACCOUNT: ${{secrets.GMAIL_ACCOUNT}}
      GMAIL_PASS: ${{secrets.GMAIL_PASS}}
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      GUILD_ID: ${{secrets.GUILD_ID}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # pip install git+https://github.com/someuser/telegram_bot_calendar.git


      - name: Run tests
        run: python -m pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
