name: pytest

# Trigger the workflow on push or pull request to the main branch
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment (Ubuntu in this case)
    env:
      MONGO_CONNECTION_URL: ${{secrets.MONGO_CONNECTION_URL}}
      DB_NAME: ${{secrets.DB_NAME}}
      TELEGRAM_API_KEY: ${{secrets.TELEGRAM_API_KEY}}
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      GUILD_ID: ${{secrets.GUILD_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up the desired Python version
        with:
          python-version: '3.12'  # Specify the Python version (e.g., 3.8 or latest 3.x)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          python -m pytest test
